-- Create users table
CREATE SCHEMA IF NOT EXISTS tic_app;

CREATE TABLE IF NOT EXISTS tic_app.USERS (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    ROLES VARCHAR(255) NOT NULL,
    PROFILE_PICTURE BYTEA
);
