name: Enforce Branch Naming Convention

on:
  create

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Branch Name
        run: |
          BRANCH_NAME="${{ github.ref }}" 
          BRANCH_NAME="${BRANCH_NAME#refs/heads/}"
          
          if [[ "$BRANCH_NAME" =~ ^TIC-[0-9]+(-[a-zA-Z0-9]+)?$ ]]; then
            echo "✅ Branch name follows the correct pattern."
          else
            echo "❌ Branch name must follow TIC-issue# or TIC-issue#-feature format (e.g., TIC-123 or TIC-123-feature)."
            exit 1
          fi
